import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import LogParser from './log_parser'
import Markdown from './markdown'
import { useState } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [isLoading, setLoading] = useState<boolean>(false);
  const [markdownContent, setMarkdownContent] = useState<string>(`
  Hi! Once you've input your raw log event and parser code, click "Simulate Parsing"!
  
  Then, I'll show you the parsed UDM event, provide an explanation, and share some suggestions and tips.
  `);

  const handleRequest = () => {
    setLoading(true);
  }

  const handleContentChange = (response: string) => {
    setLoading(false);
    setMarkdownContent(response);
  };

  return (
    <>
      <Head>
        <title>Google Chronicle Log Parser</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-8">
        <div className="flex flex-col w-full">
          <LogParser onRequest={handleRequest} onParse={handleContentChange}></LogParser><br />
          <h2 className='text-3xl mb-4'>Output parsed UDM Event</h2>
          
          {markdownContent.trim() !== '' && <Markdown content={markdownContent} />}
        </div>
        <div className='flex flex-col'>
        <div className="flex flex-row">
            <span className='text-xs italic mt-4 text-slate-400'>
              Made for <a className="link underline underline-offset-4" href="https://www.linkedin.com/in/carmela-sevilla/">Carmela Sevilla</a>. See <a className="link underline underline-offset-4" href="https://github.com/darrensapalo/chronicle-log-parser">GitHub source code</a>.
            </span>
          </div>
          <div className="flex flex-row">
            <span className='text-xs italic my-4 text-slate-400'>
              Resources: 
              <a className="link underline underline-offset-4 mx-2" href="https://cloud.google.com/chronicle/docs/preview/parser-extensions/parsing-overview">Chronicle Log Parsing</a>
              <a className="link underline underline-offset-4 mx-2" href="https://www.elastic.co/guide/en/logstash/current/advanced-pipeline.html">Parsing with Logstash</a>
              <a className="link underline underline-offset-4 mx-2" href="https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html">Grok filter plugin</a>
              <a className="link underline underline-offset-4 mx-2" href="https://cloud.google.com/chronicle/docs/reference/udm-field-list">UDM field list</a>
              
              
            </span>
          </div>
        </div>

      </main>
    </>
  )
}
